---
# 

- name: Add 24x7 monitoring 
  hosts: 
  user: root
  tasks:
   
   - name: Add monitoring
     local_action: shell curl -d "displayname=DOMAIN&url=http://LINK/admin&monitortype=URL&groupname=GROUP_NAME&pollinterval=3&timeout=30&primarylocation=California&secondarylocation=Rotterdam,London,Munich&locationfailures=3&contactgroupnames=Alert contact,All%20by%20mail&escalationGroupName=All%20by%20mail&maxfailurechecks=4&method=G&escalationDuration=30&rcaNeeded=true&availabilitystring=STRING%20" http://www.site24x7.com/api/xml/addMonitor?apikey=XXXXXXXXXXXX
