---
# 

- name: Install solr and jetty 
  hosts: 
  user: root
  tasks:

    - name: Install java
      yum: name=java-1.7.0-openjdk state=present

    - name: Create jetty group
      group: name=jetty state=present system=yes

    - name: Create jetty user
      user: name=jetty comment="Jetty user" home=/home/jetty group=jetty system=yes

    - name: Download solr
      get_url: url=http://apache.volia.net/lucene/solr/4.9.0/solr-4.9.0.tgz dest=/opt/solr-4.9.0.tgz

    - name: Download jetty
      get_url: url=http://ftp.fau.de/eclipse/jetty/9.2.1.v20140609/dist/jetty-distribution-9.2.1.v20140609.tar.gz dest=/opt/jetty-distribution-9.2.1.v20140609.tar.gz
     
    - name: Untar jetty 
      shell: tar xzf /opt/jetty-distribution-9.2.1.v20140609.tar.gz  -C /opt/; mv /opt/jetty-distribution-9.2.1.v20140609 /opt/jetty-9.2.1
    
    - name: Untar Solr
      shell: tar xzf /opt/solr-4.9.0.tgz -C /opt/; mv /opt/solr-4.9.0/example/* /opt/solr-4.9.0/; 

    - name: Move examples folders to a suitable location
      shell: cp /opt/solr-4.9.0/webapps/solr.war /opt/jetty-9.2.1/webapps/; cp -r /opt/solr-4.9.0/lib/ext/* /opt/jetty-9.2.1/lib/ext/; cp -r /opt/solr-4.9.0/solr/collection1 /opt/solr-4.9.0/; cp -r /opt/solr-4.9.0/example-schemaless/solr/collection1/* /opt/solr-4.9.0/collection1/  
   
    - name: Copy jetty config 
      copy: src=/etc/ansible/files/solr/jetty  dest=/etc/default/jetty
  
    - name: change  jetty default port
      copy: src=/etc/ansible/files/solr/http.ini  dest=/opt/jetty-9.2.1/start.d/http.ini owner=jetty

    - name: copy solrconfig.xml
      copy: src=/etc/ansible/files/solr/solrconfig.xml dest=/opt/solr-4.9.0/collection1/conf/solrconfig.xml owner=jetty
    
    - name: copy sol schema.xml
      copy: src=/etc/ansible/files/solr/schema.xml dest=/opt/solr-4.9.0/collection1/conf/schema.xml owner=jetty

    - name: copy solr logging properties
      copy: src=/etc/ansible/files/solr/logging.properties dest=/opt/jetty-9.2.1/etc/logging.properties owner=jetty
   
    - name: Create jetty start up script
      shell: ln -s /opt/jetty-9.2.1/bin/jetty.sh /etc/init.d/jetty

    - name: Modify user rights to solr/collection1
      shell: mkdir /var/log/jetty-9.2.1; chown -R jetty:jetty /opt/solr-4.9.0/; chown -R jetty:jetty /var/log/jetty-9.2.1/; chown -R jetty:jetty /opt/jetty-9.2.1

    - name: Start jetty service
      service: name=jetty state=restarted

    - name: Configure jetty to start automatically
      shell: chkconfig jetty on

    - name: Copy solr logrotate config
      copy: src=/etc/ansible/files/solr/solr dest=/etc/logrotate.d owner=root mode=644

#    - name: Iptables rule add
#      command: /sbin/iptables -A INPUT -s XXX.XXX.XXX.XXX/24 -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT

#    - name: Iptables save rules
#      command: /sbin/service iptables save


    - name : add iptables rule
      lineinfile: dest=/etc/sysconfig/iptables regexp="\-A INPUT \-j REJECT" insertafter="\-A INPUT \-j REJECT" line="-A INPUT -s XXX.XXX.XXX.XXX/24,{{ ansible_eth0.ipv4.address }} -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT"

    - name: restart iptables
      service: name=iptables state=restarted
